#pragma once

#include "stm32f767xx.h"

namespace ResetClockControl
{

static void enable_all_gpio_clocks()
{
	RCC->AHB1ENR |=
		RCC_AHB1ENR_GPIOAEN |
		RCC_AHB1ENR_GPIOBEN |
		RCC_AHB1ENR_GPIOCEN |
		RCC_AHB1ENR_GPIODEN |
		RCC_AHB1ENR_GPIOEEN |
		RCC_AHB1ENR_GPIOFEN |
		RCC_AHB1ENR_GPIOGEN |
		RCC_AHB1ENR_GPIOHEN |
		RCC_AHB1ENR_GPIOIEN |
		RCC_AHB1ENR_GPIOJEN |
		RCC_AHB1ENR_GPIOKEN;
}

}
